services:
  - type: web
    name: laravel-app
    env: php
    buildCommand: |
      composer install
      php artisan key:generate
      php artisan migrate --force
    startCommand: php artisan serve --host=0.0.0.0 --port=10000
    envVars:
      - key: APP_ENV
        value: production
      - key: APP_KEY
        generateValue: true
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: tu-host
      - key: DB_PORT
        value: 3306
      - key: DB_DATABASE
        value: tu-db
      - key: DB_USERNAME
        value: tu-usuario
      - key: DB_PASSWORD
        value: tu-password
